const getters = {
  tag: state => state.tags.tag,
  website: state => state.common.website,
  userInfo: state => state.user.userInfo,
  isCollapse: state => state.common.isCollapse,
  noOrg: state => !state.user.userInfo.orgId,
  keyCollapse: (state, getters) => getters.screen > 1 ? getters.isCollapse : false,
  screen: state => state.common.screen,
  isLock: state => state.common.isLock,
  lockPasswd: state => state.common.lockPasswd,
  tagList: state => state.tags.tagList,
  tagWel: state => state.tags.tagWel,
  access_token: state => state.user.access_token,
  refresh_token: state => state.user.refresh_token,
  expires_in: state => state.user.expires_in,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  menu: state => state.menu.menu,
  mainMenu: state => state.menu.mainMenu,
  otherMenus: state => state.menu.otherMenus,
  menusMap: state => state.menu.menusMap,
  menuPathList: state => state.menu.menuPathList,
  dictGroup: state => state.cache.dictGroup,
  contactsPyGroup: state => state.cache.contactsPyGroup,
}
export default getters
