export const SUCCESS = 0 // 成功接收数据
export const ERROR = 1 // 接收数据失败
export const BASE_URL = '/api'
export const DELETE = '删除成功'
export const CREATE = '创建成功'
export const UPDATE = '修改成功'
export const DELETE_SUCCESS = '删除成功'
export const CREATE_SUCCESS = '创建成功'
export const UPDATE_SUCCESS = '修改成功'
export const EXPORT_SUCCESS = '导出成功'
export const IMPORT_SUCCESS = '导入成功'
export const DELETE_FAILURE = '删除失败'
export const CREATE_FAILURE = '创建失败'
export const UPDATE_FAILURE = '修改失败'
export const EXPORT_FAILURE = '导出失败'
export const IMPORT_FAILURE = '导入失败'
export const IS_DELETE = '确定要删除吗'
export const MULTIPLE_DELETE_EMPTY = '未选择不能批量删除,请选择后操作'
export const EXPORT_TIMEOUT = 1000 * 60 * 30 // 30分钟
export const IMPORT_TIMEOUT = 1000 * 60 * 60 // 60分钟
