// const pageColumnObj = {
//   id: '1', // 用户ID
//   name: '张超', // 姓名
//   userName: 'zhangchao', // 用户名
//   roleName: '管理员', // 角色
//   staffId: 'GM23123', // 工号
//   position: '程序人员', // 岗位
//   externalTitle: '内部人员', // 对外头衔
//   job: '不知道', // 职务
//   title: '不知道', // 职称
//   entryTime: '', // 入职时间
//   positiveTime: '', // 转正时间
//   transferTime: '', // 调动时间
//   status: 1, // 员工状态
//   dept: '开发', // 所属部门
//   birthday: '', // 出生年月
//   sex: '男', // 性别
//   nationality: '汉族', // 民族
//   politicalStatus: '群众', // 政治面貌
//   maritalStatus: '未婚', // 婚姻状况
//   fertilityStatus: '无', // 生育状况
//   language: '汉语', // 外语水平
//   education: '大学', // 最高学历
//   graduatedSchool: '北大', // 毕业学校
//   profession: '电子', // 专业
//   graduationTime: '', // 毕业时间
//   referrer: '张绍', // 推荐人
//   accountTypes: '舟山定海', // 户口类别
//   accountLocation: '舟山定海', // 户口所在地
//   residenceAddress: '舟山定海', // 户籍地址
//   currentAddress: '舟山定海', // 现住地址
//   IDCard: '30303030303030303', // 身份证
//   phone: '1303030303', // 联系手机
//   weChat: 'lanseria', // 微信
//   qq: '564265135', // QQ
//   email: '123123@qq.com', // 邮箱
//   emergencyName: '公元', // 应急联系人
//   emergencyPhone: '12321312', // 应急联系方式
//   signingTime: '', // 劳动合同签订时间
//   benefitsStartTime: '', // 社保福利起缴时间
//   benefitsStopTime: '', // 社保福利停缴时间
//   separationTime: '', // 离职时间
// }