export const radioList = [
    {id: 'A',label: 'A'},
    {id: 'B',label: 'B'},
    {id: 'C',label: 'C'},
    {id: 'D',label: 'D'},
    {id: 'E',label: 'E'},
    {id: 'F',label: 'F'},
    {id: 'G',label: 'G'},
    {id: 'H',label: 'H'},
    {id: 'I',label: 'I'},
    {id: 'J',label: 'J'},
    {id: 'K',label: 'K'},
    {id: 'L',label: 'L'},
    {id: 'M',label: 'M'},
    {id: 'N',label: 'N'},
    {id: 'O',label: 'O'},
    {id: 'P',label: 'P'},
    {id: 'Q',label: 'Q'},
    {id: 'R',label: 'R'},
    {id: 'S',label: 'S'},
    {id: 'T',label: 'T'},
    {id: 'U',label: 'U'},
    {id: 'V',label: 'V'},
    {id: 'W',label: 'W'},
    {id: 'X',label: 'X'},
    {id: 'Y',label: 'Y'},
    {id: 'Z',label: 'Z'},
]

export const checkboxList = [
    {id: 'A',label: 'A'},
    {id: 'B',label: 'B'},
    {id: 'C',label: 'C'},
    {id: 'D',label: 'D'},
    {id: 'E',label: 'E'},
    {id: 'F',label: 'F'},
    {id: 'G',label: 'G'},
    {id: 'H',label: 'H'},
    {id: 'I',label: 'I'},
    {id: 'J',label: 'J'},
    {id: 'K',label: 'K'},
    {id: 'L',label: 'L'},
    {id: 'M',label: 'M'},
    {id: 'N',label: 'N'},
    {id: 'O',label: 'O'},
    {id: 'P',label: 'P'},
    {id: 'Q',label: 'Q'},
    {id: 'R',label: 'R'},
    {id: 'S',label: 'S'},
    {id: 'T',label: 'T'},
    {id: 'U',label: 'U'},
    {id: 'V',label: 'V'},
    {id: 'W',label: 'W'},
    {id: 'X',label: 'X'},
    {id: 'Y',label: 'Y'},
    {id: 'Z',label: 'Z'},
]

export const chooseOption = [
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
]