export const radioList = [
    {id: '0',label: 'A'},
    {id: '1',label: 'B'},
    {id: '2',label: 'C'},
    {id: '3',label: 'D'},
    {id: '4',label: 'E'},
    {id: '5',label: 'F'},
    {id: '6',label: 'G'},
    {id: '7',label: 'H'},
    {id: '8',label: 'I'},
    {id: '9',label: 'J'},
    {id: '10',label: 'K'},
    {id: '11',label: 'L'},
    {id: '12',label: 'M'},
    {id: '13',label: 'N'},
    {id: '14',label: 'O'},
    {id: '15',label: 'P'},
    {id: '16',label: 'Q'},
    {id: '17',label: 'R'},
    {id: '18',label: 'S'},
    {id: '19',label: 'T'},
    {id: '20',label: 'U'},
    {id: '21',label: 'V'},
    {id: '22',label: 'W'},
    {id: '23',label: 'X'},
    {id: '24',label: 'Y'},
    {id: '25',label: 'Z'},
]

export const checkboxList = [
    {id: '0',label: 'A'},
    {id: '1',label: 'B'},
    {id: '2',label: 'C'},
    {id: '3',label: 'D'},
    {id: '4',label: 'E'},
    {id: '5',label: 'F'},
    {id: '6',label: 'G'},
    {id: '7',label: 'H'},
    {id: '8',label: 'I'},
    {id: '9',label: 'J'},
    {id: '10',label: 'K'},
    {id: '11',label: 'L'},
    {id: '12',label: 'M'},
    {id: '13',label: 'N'},
    {id: '14',label: 'O'},
    {id: '15',label: 'P'},
    {id: '16',label: 'Q'},
    {id: '17',label: 'R'},
    {id: '18',label: 'S'},
    {id: '19',label: 'T'},
    {id: '20',label: 'U'},
    {id: '21',label: 'V'},
    {id: '22',label: 'W'},
    {id: '23',label: 'X'},
    {id: '24',label: 'Y'},
    {id: '25',label: 'Z'},
]

export const chooseOption = [
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
]